### ISSUE TITLE
local Mogrify_draw dependency?

### ISSUE THREAD

**Issue by PragTob** [zamith/charter#1]
Heyho! :)

I wanted to potentially use this for another benchee formatter but am slightly concerened about the dependencies:

```elixir
  defp deps do
    [
      {:mogrify, github: "route/mogrify", override: true},
      {:mogrify_draw, path: "../mogrify_draw"},
    ]
end
```

Seems like one would have to mogrify_draw checked out locally and rely on a non released version of mogrify? :scream: 

Thanks!
Tobi

**Comment by zamith** [comment]
Actually, that didn't have to be the case anymore. Just released a new version of `mogrify_draw` and update the dependencies here. Thanks for the heads up. 😄
